load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files(
    ["yarn_binary.sh.tpl"],
    visibility = ["//visibility:private"],
)

bzl_library(
    name = "extensions",
    srcs = ["extensions.bzl"],
    visibility = ["//yarn:__pkg__"],
    deps = [
        ":repositories",
        ":versions",
        "//yarn/private/install:repository",
        "//yarn/private/install:tarball",
    ],
)

bzl_library(
    name = "repositories",
    srcs = ["repositories.bzl"],
)

bzl_library(
    name = "versions",
    srcs = ["versions.bzl"],
)

bzl_library(
    name = "yarn_binary",
    srcs = ["yarn_binary.bzl"],
    visibility = ["//yarn:__pkg__"],
    deps = ["@bazel_skylib//lib:shell"],
)
