"""Repository rule that fetches a Yarn distribution."""

visibility(["//tests/...", "//yarn/..."])

BUILD_FILE_CONTENT = """\
# Generated by rules_yarn. Do not edit.

filegroup(
    name = "yarn",
    srcs = ["yarn.js"],
    visibility = ["//visibility:public"],
)
"""

def yarn_distribution_impl(repository_ctx):
    """Downloads `yarn.js` and exposes it as the `yarn` target.

    Args:
        repository_ctx: The repository context.

    Returns:
        Metadata declaring that the repository can be refetched reproducibly.
    """
    repository_ctx.download(
        url = repository_ctx.attr.urls,
        output = "yarn.js",
        integrity = repository_ctx.attr.integrity,
    )
    repository_ctx.file("BUILD.bazel", BUILD_FILE_CONTENT)
    return repository_ctx.repo_metadata(reproducible = True)

yarn_distribution = repository_rule(
    implementation = yarn_distribution_impl,
    doc = "Fetches a standalone Yarn bundle and exposes it as the `yarn` target.",
    attrs = {
        "integrity": attr.string(
            doc = "Subresource Integrity digest that the downloaded bundle must match.",
            mandatory = True,
        ),
        "urls": attr.string_list(
            doc = "Mirrors that serve the same Yarn bundle.",
            mandatory = True,
        ),
    },
)
