#!{{SHELL}}
# Generated by rules_yarn's yarn_binary rule. Runs the selected Yarn
# distribution with the Bazel-managed Node.js runtime.

# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

if ! node="$(rlocation {{NODE_RLOCATION_PATH}})" || [[ -z "$node" ]]; then
  echo >&2 "ERROR: rules_yarn: cannot find the Node.js runtime in the runfiles"
  exit 1
fi
if ! yarn="$(rlocation {{YARN_RLOCATION_PATH}})" || [[ -z "$yarn" ]]; then
  echo >&2 "ERROR: rules_yarn: cannot find the Yarn entry point in the runfiles"
  exit 1
fi

# The paths must stay valid after the directory change below.
if [[ "$node" != /* ]]; then
  node="$PWD/$node"
fi
if [[ "$yarn" != /* ]]; then
  yarn="$PWD/$yarn"
fi

# Ignore `yarnPath` in project configuration so that the selected distribution
# runs, and keep Yarn from sending telemetry.
export YARN_IGNORE_PATH=1
export YARN_ENABLE_TELEMETRY=0

# `bazel run` starts binaries in their runfiles tree and records the caller's
# directory in BUILD_WORKING_DIRECTORY.
if [[ -n "${BUILD_WORKING_DIRECTORY:-}" ]]; then
  cd "$BUILD_WORKING_DIRECTORY"
fi

exec "$node" "$yarn" "$@"
