"""Repository rule that installs a Yarn project's locked dependencies."""

visibility(["//yarn/..."])

_NODE = {
    "darwin_amd64": Label("@nodejs_darwin_amd64//:bin/nodejs/bin/node"),
    "darwin_arm64": Label("@nodejs_darwin_arm64//:bin/nodejs/bin/node"),
    "linux_amd64": Label("@nodejs_linux_amd64//:bin/nodejs/bin/node"),
    "linux_arm64": Label("@nodejs_linux_arm64//:bin/nodejs/bin/node"),
}

_PROGRAMS = [
    Label("//yarn/private/install:archive.js"),
    Label("//yarn/private/install:check.js"),
    Label("//yarn/private/install:conditions.js"),
    Label("//yarn/private/install:driver.js"),
    Label("//yarn/private/install:layout.js"),
    Label("//yarn/private/install:lockfile.js"),
    Label("//yarn/private/install:syml.js"),
    Label("//yarn/private/install:yarnrc.js"),
]

_JS_YAML = Label("@js_yaml//:index.js")

def _host(repository_ctx):
    name = repository_ctx.os.name.lower()
    arch = repository_ctx.os.arch.lower()
    os = "linux" if name.startswith("linux") else "darwin" if name.startswith("mac os") else None
    cpu = {"aarch64": "arm64", "amd64": "amd64", "arm64": "arm64", "x86_64": "amd64"}.get(arch)
    if not os or not cpu:
        fail("yarn.install cannot run on this host ({}, {}): installation runs on Linux and macOS, on x86-64 and ARM64.".format(name, arch))
    return "{}_{}".format(os, cpu)

def _project_path(label, root):
    """The path of `label` relative to the project root, the package of package.json."""
    full = "{}/{}".format(label.package, label.name) if label.package else label.name
    if root.package == "":
        relative = full
    elif full.startswith(root.package + "/"):
        relative = full[len(root.package) + 1:]
    else:
        fail("{} is not inside the project at {}".format(label, root))

    # Label.repo_name, not the deprecated Label.workspace_name (Bazel 8.3.0,
    # src/main/java/com/google/devtools/build/lib/cmdline/Label.java).
    if label.repo_name != root.repo_name:
        fail("{} is not in the same repository as {}".format(label, root))
    return relative

def _stage(repository_ctx, label, destination):
    path = repository_ctx.path(label)
    repository_ctx.watch(path)
    repository_ctx.symlink(path, destination)

def _run(repository_ctx, node, arguments, timeout):
    # Nothing from Bazel's environment reaches the driver; it gives Yarn an
    # environment of its own.
    environment = {name: None for name in repository_ctx.os.environ}
    result = repository_ctx.execute(
        [node] + arguments,
        environment = environment,
        quiet = True,
        timeout = timeout,
    )
    if result.return_code != 0:
        fail("yarn.install driver failed:\n{}{}".format(result.stdout, result.stderr))

def _build_file(repository_ctx, body):
    repository_ctx.file("BUILD.bazel", """\
# Generated by rules_yarn. Do not edit.

load("@rules_yarn//yarn:defs.bzl", "yarn_binary")
load(":node_modules.bzl", "yarn_install_error", "yarn_node_modules")

{body}

filegroup(
    name = "pin_entry",
    srcs = ["pin.cjs"],
    data = [
        "pin_config.json",
        "yarn.js",
    ],
)

yarn_binary(
    name = "pin",
    yarn = ":pin_entry",
)
""".format(body = body))

def _yarn_install_repository_impl(repository_ctx):
    attr = repository_ctx.attr
    node = repository_ctx.path(_NODE[_host(repository_ctx)])
    driver = repository_ctx.path(Label("//yarn/private/install:driver.js"))

    # The driver and the modules it loads decide the installed tree as much as
    # the project does, so a change to any of them — an upgrade of rules_yarn
    # that changes only JavaScript — has to install again. `path` alone does
    # not make Bazel watch a file.
    for program in _PROGRAMS:
        repository_ctx.watch(repository_ctx.path(program))

    # The YAML parser Yarn uses, by which the driver and the pin target read
    # yarn.lock and .yarnrc.yml; another version has to install again.
    js_yaml = repository_ctx.path(_JS_YAML)
    repository_ctx.watch_tree(js_yaml.dirname)
    yarn = repository_ctx.path(attr.yarn)
    root = attr.package_json

    repository_ctx.symlink(Label("//yarn/private/install:node_modules.bzl"), "node_modules.bzl")
    repository_ctx.symlink(Label("//yarn/private/install:pin.cjs"), "pin.cjs")
    repository_ctx.symlink(yarn, "yarn.js")

    # The pin target runs in the developer's checkout, so it is given paths
    # relative to the workspace root.
    repository_ctx.file("pin_config.json", json.encode({
        "installName": attr.install_name,
        "jsYaml": str(js_yaml),
        "lockfile": _workspace_path(attr.lockfile),
        "pins": _workspace_path(attr.pins),
        "project": root.package,
    }))

    project = "stage/project"
    _stage(repository_ctx, root, project + "/package.json")
    _stage(repository_ctx, attr.lockfile, project + "/yarn.lock")
    workspaces = []
    for label in attr.workspaces:
        relative = _project_path(label, root)
        if not relative.endswith("/package.json"):
            fail("{} in `workspaces` is not a package.json".format(label))
        workspaces.append(relative[:-len("/package.json")])
        _stage(repository_ctx, label, project + "/" + relative)
    patches = []
    for label in attr.patches:
        relative = _project_path(label, root)
        patches.append(relative)
        _stage(repository_ctx, label, project + "/" + relative)
    yarnrc = None
    if attr.yarnrc:
        _stage(repository_ctx, attr.yarnrc, "stage/yarnrc.yml")
        yarnrc = str(repository_ctx.path("stage/yarnrc.yml"))
    pins = repository_ctx.path(attr.pins)
    repository_ctx.watch(pins)

    by_resolution = {resolution: label for label, resolution in attr.tarballs.items()}
    config = {
        "architectures": attr.supported_architectures,
        "cacheVersion": attr.cache_version,
        "installName": attr.install_name,
        "jsYaml": str(js_yaml),
        "out": str(repository_ctx.path(".")),
        "patches": patches,
        "pins": str(pins),
        "project": str(repository_ctx.path(project)),
        "workspaces": workspaces,
        "yarn": str(yarn),
        "yarnVersion": attr.yarn_version,
        "yarnrc": yarnrc,
    }
    repository_ctx.file("plan_config.json", json.encode(config))
    _run(repository_ctx, node, [driver, "plan", "plan_config.json"], timeout = 600)
    plan = json.decode(repository_ctx.read("plan.json"))
    errors = plan["errors"]
    tarballs = {}
    if not errors:
        for resolution in plan["tarballs"]:
            if resolution not in by_resolution:
                errors.append("yarn.lock entry {} has no fetched tarball; run `bazel run @{}//:pin`".format(resolution, attr.install_name))
                continue
            tarballs[resolution] = str(repository_ctx.path(by_resolution[resolution]))
    if not errors:
        config["tarballs"] = tarballs
        repository_ctx.file("install_config.json", json.encode(config))
        _run(repository_ctx, node, [driver, "install", "install_config.json"], timeout = 3600)
        if repository_ctx.path("errors.json").exists:
            errors = json.decode(repository_ctx.read("errors.json"))

    if errors:
        _build_file(repository_ctx, """\
yarn_install_error(
    name = "node_modules",
    message = {message},
    visibility = ["//visibility:public"],
)""".format(message = repr("yarn.install(name = \"{}\") cannot install the project:\n  - {}".format(attr.install_name, "\n  - ".join(errors)))))
        return None

    layout = json.decode(repository_ctx.read("layout.json"))
    _build_file(repository_ctx, """\
yarn_node_modules(
    name = "node_modules",
    architectures = {architectures},
    bins = {bins},
    links = {links},
    node_version = {node},
    packages = {packages},
    workspace_links = {workspace_links},
    yarn_version = {yarn},
    visibility = ["//visibility:public"],
)""".format(
        architectures = repr({k: v for k, v in layout["architectures"].items() if v != None}),
        bins = repr({b["path"]: b["target"] for b in layout["bins"]}),
        links = repr({link["path"]: link["target"] for link in layout["links"]}),
        node = repr(layout["node"]),
        packages = repr({p["archive"]: p["path"] for p in layout["packages"]}),
        workspace_links = repr({link["path"]: link["workspace"] for link in layout["workspaceLinks"]}),
        yarn = repr(layout["yarn"]),
    ))

    # Not marked reproducible (`repo_metadata`, Bazel 8.3.0
    # StarlarkRepositoryContext.java): that would let Bazel reuse these
    # contents across workspaces, and they hold what such reuse must not carry
    # over — the host's platform packages and Node.js, and absolute paths into
    # this output base. The tarballs it installs from are pinned by integrity
    # and cached on their own.
    return None

def _workspace_path(label):
    return "{}/{}".format(label.package, label.name) if label.package else label.name

yarn_install_repository = repository_rule(
    implementation = _yarn_install_repository_impl,
    doc = "Installs a Yarn project's locked dependencies, as directory and symlink artifacts.",
    attrs = {
        "cache_version": attr.string(mandatory = True),
        "install_name": attr.string(mandatory = True),
        "lockfile": attr.label(mandatory = True, allow_single_file = True),
        "package_json": attr.label(mandatory = True, allow_single_file = True),
        "patches": attr.label_list(allow_files = True),
        "pins": attr.label(mandatory = True, allow_single_file = True),
        "supported_architectures": attr.string_list_dict(),
        "tarballs": attr.label_keyed_string_dict(allow_files = True),
        "workspaces": attr.label_list(allow_files = True),
        "yarn": attr.label(mandatory = True, allow_single_file = True),
        "yarn_version": attr.string(mandatory = True),
        "yarnrc": attr.label(allow_single_file = True),
    },
)
