"""Repository rule that fetches one pinned npm tarball."""

visibility(["//yarn/..."])

def _yarn_tarball_impl(repository_ctx):
    repository_ctx.download(
        url = [repository_ctx.attr.url],
        output = "package.tgz",
        integrity = repository_ctx.attr.integrity,
    )
    repository_ctx.file("BUILD.bazel", """\
# Generated by rules_yarn. Do not edit.

exports_files(["package.tgz"], visibility = ["//visibility:public"])
""")
    return repository_ctx.repo_metadata(reproducible = True)

yarn_tarball = repository_rule(
    implementation = _yarn_tarball_impl,
    doc = "Fetches one npm tarball with the integrity its pin records, through Bazel's downloader.",
    attrs = {
        "integrity": attr.string(mandatory = True),
        "url": attr.string(mandatory = True),
    },
)
