load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("@rules_yarn//yarn:defs.bzl", "yarn_binary")

yarn_binary(
    name = "yarn",
    yarn = "@yarn",
)

sh_test(
    name = "yarn_version_test",
    srcs = ["yarn_version_test.sh"],
    args = ["$(rlocationpath :yarn)"],
    data = [":yarn"],
    tags = ["block-network"],
    deps = ["@rules_shell//shell/runfiles"],
)
