load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "archive_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath archive_test.js)",
    ],
    data = [
        "archive_test.js",
        "//yarn/private/install:archive.js",
        "@nodejs//:node_bin",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "lockfile_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath lockfile_test.js)",
        "$(rlocationpath @js_yaml//:index.js)",
    ],
    data = [
        "lockfile_test.js",
        "//yarn/private/install:lockfile.js",
        "//yarn/private/install:syml.js",
        "@js_yaml",
        "@js_yaml//:index.js",
        "@nodejs//:node_bin",
    ] + glob(["testdata/**"]),
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "check_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath check_test.js)",
        "$(rlocationpath @js_yaml//:index.js)",
    ],
    data = [
        "check_test.js",
        "//yarn/private/install:check.js",
        "//yarn/private/install:lockfile.js",
        "//yarn/private/install:syml.js",
        "@js_yaml",
        "@js_yaml//:index.js",
        "@nodejs//:node_bin",
    ] + glob(["testdata/**"]),
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "layout_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath layout_test.js)",
    ],
    data = [
        "layout_test.js",
        "//yarn/private/install:layout.js",
        "@nodejs//:node_bin",
    ] + glob(["testdata/**"]),
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "conditions_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath conditions_test.js)",
        "$(rlocationpath @js_yaml//:index.js)",
    ],
    data = [
        "conditions_test.js",
        "//yarn/private/install:conditions.js",
        "//yarn/private/install:lockfile.js",
        "//yarn/private/install:syml.js",
        "@js_yaml",
        "@js_yaml//:index.js",
        "@nodejs//:node_bin",
    ] + glob(["testdata/**"]),
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "yarnrc_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath yarnrc_test.js)",
        "$(rlocationpath @js_yaml//:index.js)",
    ],
    data = [
        "yarnrc_test.js",
        "//yarn/private/install:syml.js",
        "//yarn/private/install:yarnrc.js",
        "@js_yaml",
        "@js_yaml//:index.js",
        "@nodejs//:node_bin",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "watched_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath watched_test.js)",
    ],
    data = [
        "watched_test.js",
        "//yarn/private/install:archive.js",
        "//yarn/private/install:check.js",
        "//yarn/private/install:conditions.js",
        "//yarn/private/install:driver.js",
        "//yarn/private/install:layout.js",
        "//yarn/private/install:lockfile.js",
        "//yarn/private/install:repository.bzl",
        "//yarn/private/install:syml.js",
        "//yarn/private/install:yarnrc.js",
        "@nodejs//:node_bin",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "driver_test",
    size = "small",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath driver_test.js)",
        "$(rlocationpath @js_yaml//:index.js)",
    ],
    data = [
        "driver_test.js",
        "//yarn/private/install:archive.js",
        "//yarn/private/install:check.js",
        "//yarn/private/install:conditions.js",
        "//yarn/private/install:driver.js",
        "//yarn/private/install:layout.js",
        "//yarn/private/install:lockfile.js",
        "//yarn/private/install:syml.js",
        "//yarn/private/install:yarnrc.js",
        "@js_yaml",
        "@js_yaml//:index.js",
        "@nodejs//:node_bin",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

sh_test(
    name = "yarnrc_yarn_test",
    size = "medium",
    srcs = ["node_test.sh"],
    args = [
        "$(rlocationpath @nodejs//:node_bin)",
        "$(rlocationpath yarnrc_yarn_test.js)",
        "$(rlocationpath @js_yaml//:index.js)",
        "$(rlocationpath @yarn)",
    ],
    data = [
        "yarnrc_yarn_test.js",
        "//yarn/private/install:archive.js",
        "//yarn/private/install:check.js",
        "//yarn/private/install:conditions.js",
        "//yarn/private/install:driver.js",
        "//yarn/private/install:layout.js",
        "//yarn/private/install:lockfile.js",
        "//yarn/private/install:syml.js",
        "//yarn/private/install:yarnrc.js",
        "@js_yaml",
        "@js_yaml//:index.js",
        "@nodejs//:node_bin",
        "@yarn",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)
