"use strict";
// The lockfile parser reads exactly the subset of YAML that Yarn 4.18.0's
// `stringifySyml` writes (packages/yarnpkg-parsers/sources/syml.ts), keeping
// every scalar a string as Yarn's own FAILSAFE_SCHEMA reading does, and refuses
// anything outside it rather than guessing.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const lockfile = require("../../yarn/private/install/lockfile.js");

// The js-yaml Yarn reads YAML with, as the ruleset fetches it (node_test.sh).
const yaml = require(process.env.JS_YAML);
const parseLockfile = (text) => lockfile.parseLockfile(text, yaml);

const fixture = (name) => fs.readFileSync(path.join(__dirname, "testdata", name), "utf8");

test("a real lockfile: metadata, every entry, nested fields", () => {
  const lock = parseLockfile(fixture("esbuild_typescript.lock"));
  assert.deepEqual(lock.metadata, {version: "10", cacheKey: "10c0"});
  // 30 descriptors, counted independently by splitting the quoted top-level keys.
  assert.equal(Object.keys(lock.entries).length, 30);
  const ts = lock.entries['typescript@patch:typescript@npm%3A5.6.3#optional!builtin<compat/typescript>'];
  assert.equal(ts.resolution, "typescript@patch:typescript@npm%3A5.6.3#optional!builtin<compat/typescript>::version=5.6.3&hash=8c6c40");
  assert.deepEqual(ts.bin, {tsc: "bin/tsc", tsserver: "bin/tsserver"});
  const linux = lock.entries["@esbuild/linux-x64@npm:0.25.0"];
  assert.equal(linux.conditions, "os=linux & cpu=x64");
  assert.equal(linux.checksum, undefined);
});

test("an entry listed under several descriptors is reachable by each", () => {
  const lock = parseLockfile(fixture("workspaces_peers.lock"));
  const b = lock.entries["b@workspace:packages/b"];
  assert.equal(lock.entries["b@workspace:*"], b);
  assert.equal(b.resolution, "b@workspace:packages/b");
  assert.deepEqual(b.dependencies, {"is-number": "npm:7.0.0"});
  assert.equal(lock.packages.filter((p) => p.resolution === "b@workspace:packages/b").length, 1);
});

test("scalars stay strings, as Yarn reads them", () => {
  const lock = parseLockfile("__metadata:\n  version: 10\n  cacheKey: 10c0\n\n\"x@npm:1.0.0\":\n  version: 1.0.0\n  resolution: \"x@npm:1.0.0\"\n  dependenciesMeta:\n    fsevents:\n      optional: true\n");
  assert.equal(lock.metadata.version, "10");
  assert.equal(lock.entries["x@npm:1.0.0"].dependenciesMeta.fsevents.optional, "true");
});

test("quoted keys and values are read as JSON strings", () => {
  const lock = parseLockfile('__metadata:\n  version: 10\n\n"q@npm:1.0.0":\n  version: 1.0.0\n  resolution: "q@npm:1.0.0"\n  bin:\n    "we\\"ird: name": "bin/a b.js"\n');
  assert.deepEqual(lock.entries["q@npm:1.0.0"].bin, {'we"ird: name': "bin/a b.js"});
});

test("a quoted string holding U+2028 is read, as js-yaml reads it", () => {
  // JSON.stringify leaves U+2028 unescaped, so Yarn's writer can emit it raw.
  const lock = parseLockfile('__metadata:\n  version: 10\n\n"u@npm:1.0.0":\n  version: 1.0.0\n  resolution: "u@npm:1.0.0"\n  bin:\n    "a\u2028b": "c"\n');
  assert.deepEqual(lock.entries["u@npm:1.0.0"].bin, {"a\u2028b": "c"});
});

test("a key longer than 1024 characters, written in the explicit-key form", () => {
  const key = Array.from({length: 120}, (_, i) => `long@npm:^1.${i}.0`).join(", ");
  assert.ok(key.length > 1024);
  const lock = parseLockfile(`__metadata:\n  version: 10\n\n? ${JSON.stringify(key)}\n:\n  version: 1.5.0\n  resolution: "long@npm:1.5.0"\n`);
  assert.equal(lock.entries["long@npm:^1.0.0"].resolution, "long@npm:1.5.0");
  assert.equal(lock.entries["long@npm:^1.119.0"].resolution, "long@npm:1.5.0");
});

test("a list of scalars", () => {
  const lock = parseLockfile('__metadata:\n  version: 10\n\n"l@npm:1.0.0":\n  version: 1.0.0\n  resolution: "l@npm:1.0.0"\n  things:\n    - a\n    - "b c"\n  none: []\n');
  assert.deepEqual(lock.entries["l@npm:1.0.0"].things, ["a", "b c"]);
  assert.deepEqual(lock.entries["l@npm:1.0.0"].none, []);
});

test("a key named __proto__ is stored as data", () => {
  const lock = parseLockfile('__metadata:\n  version: 10\n\n"p@npm:1.0.0":\n  version: 1.0.0\n  resolution: "p@npm:1.0.0"\n  dependencies:\n    __proto__: "npm:1.0.0"\n');
  assert.ok(Object.prototype.hasOwnProperty.call(lock.entries["p@npm:1.0.0"].dependencies, "__proto__"));
});

test("a Yarn 1 lockfile is named as one", () => {
  const legacy = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\nis-number@^7.0.0:\n  version "7.0.0"\n';
  assert.throws(() => parseLockfile(legacy), /Yarn 1 lockfile/);
});

test("a lockfile without metadata is refused", () => {
  assert.throws(() => parseLockfile('"x@npm:1.0.0":\n  version: 1.0.0\n'), /__metadata/);
});

test("text that is not YAML is refused, saying so", () => {
  assert.throws(() => parseLockfile('__metadata:\n  version: "10\n'), /yarn\.lock cannot be read as YAML/);
  assert.throws(() => parseLockfile("__metadata:\n\tversion: 10\n"), /yarn\.lock cannot be read as YAML/);
});

test("YAML is read as Yarn reads it: a comment is no part of a value, and a repeated key takes its last value", () => {
  const lock = parseLockfile('__metadata:\n  version: 10\n  version: 11\n\n"x@npm:1.0.0":\n  version: 1.0.0 # comment\n  resolution: "x@npm:1.0.0"\n');
  assert.equal(lock.metadata.version, "11");
  assert.equal(lock.entries["x@npm:1.0.0"].version, "1.0.0");
});

test("a document that is not a mapping is refused as Yarn refuses it", () => {
  assert.throws(() => parseLockfile("- a\n- b\n"), /expected an indexed object, got an array/);
  assert.throws(() => parseLockfile("just text\n"), /expected an indexed object, got a string/);
});
